// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zh.all.hello

object HelloProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
//    com.google.protobuf.wrappers.WrappersProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    com.zh.all.hello.Person,
    com.zh.all.hello.ToBeGreeted,
    com.zh.all.hello.Greeting
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """CgtoZWxsby5wcm90bxIKY29tLnpoLmFsbBoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3RvGhVzY2FsYXBiL3NjYWxhc
  GIucHJvdG8iHAoGUGVyc29uEhIKBG5hbWUYASABKAlSBG5hbWUiaQoLVG9CZUdyZWV0ZWQSKgoGcGVyc29uGAEgASgLMhIuY29tL
  npoLmFsbC5QZXJzb25SBnBlcnNvbhIuCgNtc2cYAiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWVSA21zZyIkCghHc
  mVldGluZxIYCgdtZXNzYWdlGAEgASgJUgdtZXNzYWdlMkkKCkhlbGxvV29ybGQSOwoIU2F5SGVsbG8SFy5jb20uemguYWxsLlRvQ
  mVHcmVldGVkGhQuY29tLnpoLmFsbC5HcmVldGluZyIAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      com.google.protobuf.wrappers.WrappersProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}